language: minimal
os: linux
dist: focal

jobs:
  fast_finish: true

  include:
    - name: Test locally
      language: python
      python: '3.6'
      script: ./.travis/local/test.sh
    - name: Test in Docker
      services: [docker]
      script: ./.travis/docker/test.sh
    - stage: publish
      name: 'Docker: build & publish multi-arch images'
      if: branch = master
      services: [docker]
      # buildx isn't installed on Focal.
      before_install: make buildx/install
      script: make login && make buildx/create && make buildx/push
